### ISSUE TITLE
Use aiodocker in other aio-libs projects

### ISSUE THREAD

**Issue by jettify** [aio-libs/aiodocker#21]
Several `aio-libs` projects use docker for testing, for example aiopg/aioodbc/aiohttp_admin etc. I think it is good idea to switch from `dockerpy` to `aiodocker`. This way `aiodocker` will be tested on each PR there, and bugs can be found faster.

I thinks `aioodbc` project is good candidated to start with, since it is not widely used, and we can experiment. https://github.com/aio-libs/aioodbc/blob/dc26608e4155b69c111f44a317a623ba52c79c6c/tests/conftest.py#L73-L113

**Comment by achimnol** [comment]
Good idea. I will make some time to write PRs with simple cases soon.

**Comment by achimnol** [comment]
I just tried to install aioodbc for development, but got an error below:
```

Collecting sphinxcontrib-asyncio==0.2.0 (from -r requirements-dev.txt (line 11))
  Using cached sphinxcontrib-asyncio-0.2.0.tar.gz
    Complete output from command python setup.py egg_info:
    /Users/joongi/Projects/3rdparties/aioodbc/venv/lib/python3.6/site-packages/setuptools/extern/__init__.py:1: UserWarning: Module sphinxcontrib was already imported from None, but /private/var/folders/xh/tls3522x3291zjmtg2fmk0kc0000gn/T/pip-build-nolz12ih/sphinxcontrib-asyncio is being added to sys.path
      from pkg_resources.extern import VendorImporter
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/Users/joongi/Projects/3rdparties/aioodbc/venv/lib/python3.6/site-packages/setuptools/__init__.py", line 10, in <module>
        from setuptools.extern.six.moves import filter, filterfalse, map
      File "/Users/joongi/Projects/3rdparties/aioodbc/venv/lib/python3.6/site-packages/setuptools/extern/__init__.py", line 1, in <module>
        from pkg_resources.extern import VendorImporter
      File "/Users/joongi/Projects/3rdparties/aioodbc/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3017, in <module>
        @_call_aside
      File "/Users/joongi/Projects/3rdparties/aioodbc/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3003, in _call_aside
        f(*args, **kwargs)
      File "/Users/joongi/Projects/3rdparties/aioodbc/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3045, in _initialize_master_working_set
        dist.activate(replace=False)
      File "/Users/joongi/Projects/3rdparties/aioodbc/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2577, in activate
        declare_namespace(pkg)
      File "/Users/joongi/Projects/3rdparties/aioodbc/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2151, in declare_namespace
        _handle_ns(packageName, path_item)
      File "/Users/joongi/Projects/3rdparties/aioodbc/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2091, in _handle_ns
        _rebuild_mod_path(path, packageName, module)
      File "/Users/joongi/Projects/3rdparties/aioodbc/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2120, in _rebuild_mod_path
        orig_path.sort(key=position_in_sys_path)
    AttributeError: '_NamespacePath' object has no attribute 'sort'
```
Do you know how to workaround/solve this?

**Comment by achimnol** [comment]
After digging down to [this](https://github.com/pypa/pip/issues/4216), simply upgrading my venv's setuptools to 35.0.2 resolved this issue. :)

**Comment by achimnol** [comment]
It seems that aioodbc targets Python 3.5+ while aiodocker targets Python 3.6+.
I can rewrite the test fixtures but this would raise the minimum Python version requirement for aioodbc to Python 3.6+. Would it be okay?

**Comment by jettify** [comment]
sure

**Comment by achimnol** [comment]
This work turns out to be non-trivial, due the scope conflicts of test fixtures.
I'm trying to workaround it using `pytest-asyncio`, but several test cases such as `test_default_event_loop` seem to manually `asyncio.set_event_loop()` -- I'm not sure to remove such test cases.
I have no experience on making `pytest-asyncio` to run with multiple event loop implementations.
Could you give me some guides on this?

**Comment by jettify** [comment]
Could you show scoping issue? You mean issue with loop to be function scope and rest of fixtures session? `pytest-asyncio` will not resolve it. Just create new fixture with session scope say `session_loop` and use it only in aiodocker session fixtures.

```
@pytest.yield_fixture(scope='session')
def session_loop(loop_type):
    if loop_type == 'uvloop':
        loop = uvloop.new_event_loop()
    else:
        loop = asyncio.new_event_loop()
    yield loop
    loop.close()
```

**Comment by achimnol** [comment]
I have resolved all issues and posted the PR. Please check it out! :)

**Comment by jettify** [comment]
Now `aioodbc` project uses `aiodocker` for creating testing infrastructure. Thanks @achimnol !
