### ISSUE TITLE
Monitoring events may return None and unclean exit

### ISSUE THREAD

**Issue by cecton** [aio-libs/aiodocker#34]
# Description

I wanted to check something in particular: what happens if you only monitor events and the DOCKER_HOST is set to something unreachable.

# Current Behavior

I receive an invalid event, plus the script waits for nothing and if I interrupt it I get an unclean exit.

# Excepted Behavior

The script should not even start, it should notice that the connection cannot be made. Also it should exit cleanly.

# How To Reproduce

To do the test, I picked the example `events.py` and removed about everything except the loop:

```python
#!/usr/bin/env python3

import asyncio
from aiodocker.docker import Docker
from aiodocker.exceptions import DockerError


async def demo(docker):

    subscriber = docker.events.subscribe()

    while True:
        event = await subscriber.get()
        print(f"event: {event!r}")


if __name__ == '__main__':
    loop = asyncio.get_event_loop()
    docker = Docker()
    try:
        # start a monitoring task.
        event_task = loop.create_task(docker.events.run())
        # do our stuffs.
        loop.run_until_complete(demo(docker))
        # explicitly stop monitoring.
        event_task.cancel()
    finally:
        loop.run_until_complete(docker.close())
        loop.close()
```

Then I run the script with:

```
DOCKER_HOST=tcp://127.0.0.1:666 ./events.py
```

And I first get an invalid event:

```
event: None
```

Then the script enters the `while True` loop and wait forever without output unless I interrupt the process.

```
^CTraceback (most recent call last):
  File "/tmp/events.py", line 24, in <module>
    loop.run_until_complete(demo(docker))
  File "/usr/lib/python3.6/asyncio/base_events.py", line 454, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.6/asyncio/base_events.py", line 421, in run_forever
    self._run_once()
  File "/usr/lib/python3.6/asyncio/base_events.py", line 1389, in _run_once
    event_list = self._selector.select(timeout)
  File "/usr/lib/python3.6/selectors.py", line 445, in select
    fd_event_list = self._epoll.poll(timeout, max_ev)
KeyboardInterrupt
Task exception was never retrieved
future: <Task finished coro=<DockerEvents.run() done, defined at /home/cecile/.local/lib/python3.6/site-packages/aiodocker-0.7-py3.6.egg/aiodocker/docker.py:512> exception=ClientConnectorError(111, "Cannot connect to host 127.0.0.1:666 ssl:False [Can not connect to 127.0.0.1:666 [Connect call failed ('127.0.0.1', 666)]]")>
Traceback (most recent call last):
  File "/home/cecile/.local/lib/python3.6/site-packages/aiohttp/connector.py", line 651, in _create_direct_connection
    local_addr=self._local_addr)
  File "/usr/lib/python3.6/asyncio/base_events.py", line 776, in create_connection
    raise exceptions[0]
  File "/usr/lib/python3.6/asyncio/base_events.py", line 763, in create_connection
    yield from self.sock_connect(sock, address)
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 451, in sock_connect
    return (yield from fut)
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 481, in _sock_connect_cb
    raise OSError(err, 'Connect call failed %s' % (address,))
ConnectionRefusedError: [Errno 111] Connect call failed ('127.0.0.1', 666)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/cecile/.local/lib/python3.6/site-packages/aiohttp/connector.py", line 374, in connect
    proto = yield from self._create_connection(req)
  File "/home/cecile/.local/lib/python3.6/site-packages/aiohttp/connector.py", line 628, in _create_connection
    _, proto = yield from self._create_direct_connection(req)
  File "/home/cecile/.local/lib/python3.6/site-packages/aiohttp/connector.py", line 678, in _create_direct_connection
    (req.host, req.port, exc.strerror)) from exc
aiohttp.client_exceptions.ClientConnectorError: [Errno 111] Can not connect to 127.0.0.1:666 [Connect call failed ('127.0.0.1', 666)]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/cecile/.local/lib/python3.6/site-packages/aiodocker-0.7-py3.6.egg/aiodocker/docker.py", line 525, in run
    params=params,
  File "/home/cecile/.local/lib/python3.6/site-packages/aiodocker-0.7-py3.6.egg/aiodocker/docker.py", line 121, in _query
    data=data, **kwargs)
  File "/home/cecile/.local/lib/python3.6/site-packages/aiohttp/client.py", line 621, in __await__
    resp = yield from self._coro
  File "/home/cecile/.local/lib/python3.6/site-packages/aiohttp/client.py", line 225, in _request
    conn = yield from self._connector.connect(req)
  File "/home/cecile/.local/lib/python3.6/site-packages/aiohttp/connector.py", line 379, in connect
    .format(key, exc.strerror)) from exc
aiohttp.client_exceptions.ClientConnectorError: [Errno 111] Cannot connect to host 127.0.0.1:666 ssl:False [Can not connect to 127.0.0.1:666 [Connect call failed ('127.0.0.1', 666)]]
Exception ignored in: <coroutine object demo at 0x7f9912428f68>
Traceback (most recent call last):
  File "/tmp/events.py", line 13, in demo
  File "/home/cecile/.local/lib/python3.6/site-packages/aiodocker-0.7-py3.6.egg/aiodocker/channel.py", line 14, in get
  File "/usr/lib/python3.6/asyncio/queues.py", line 169, in get
  File "/usr/lib/python3.6/asyncio/base_events.py", line 573, in call_soon
  File "/usr/lib/python3.6/asyncio/base_events.py", line 357, in _check_closed
RuntimeError: Event loop is closed
```

**Comment by cecton** [comment]
Apparently the `None` is done on purpose:

```python
            # signal termination to subscribers
            await self.channel.publish(None)
```

So the example should be corrected to:

```python
    while True:
        event = await subscriber.get()
        if event is None:
            break
        print(f"event: {event!r}")
```

**Comment by cecton** [comment]
I think you could also handle the Docker events task from the Docker instance itself: create the task and store it in an attribute. When the Docker instance is closed, the task is closed too. To make things even more smarter, we can create the task only when someone subscribe to the DockerEvent's channel.

What do you think? I can make a PR if you want.

**Comment by barrachri** [comment]
@cecton sorry I closed this :/

I'd be happy to see your PR :)

**Comment by cecton** [comment]
@barrachri are you sure you have merged that where you wanted to merge it? I see it merged on a forked repostiory.

**Comment by barrachri** [comment]
Hello @cecton, yes https://github.com/aio-libs/aiodocker/commits/master

**Comment by cecton** [comment]
@barrachri oh my bad again sorry, I was pulling the wrong remote.
